# -*- coding: utf-8 -*-
"""untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/muhammadqodir1313/0cfb9fcad74b2dab38906e9c7b8a080b/untitled1.ipynb
"""

import pandas as pd
our_teachers=pd.DataFrame({
                  "FISH":[   "Xalilov D. A. ", "Qadamova Z. E.","JO‘RAYEVA G. F", "TILLABOYEV M. G.", " XONTO‘RAYEV S. I.","Abdullayeva M. R. "," DJALILOV M. L.","QURBONOVA G. M.","TURDIMATOV M. M.","RAXMATOV R. R." ],
                  "Fani":[ "Sun'iy intellekt asoslari", "Sun'iy intellekt asoslari","Elektronika va sxemalar","Elektronika va sxemalar", "Ma'lumotlar tuzilmasi va algoritmlar","Ma'lumotlar tuzilmasi va algoritmlar","Kompyuterni tashkil etish","Kompyuterni tashkil etish","Kiberxavfsizlik asoslari","Kiberxavfsizlik asoslari"],
                  "Mashg'ulot turi":[ "Ma'ruza", "Amaliy", "Ma'ruza", "Amaliy", "Ma'ruza", "Amaliy","Ma'ruza", "Amaliy","Ma'ruza", "Amaliy", ],
                  "my_respect":[  'ha','ha','ha','ha','ha','ha','ha','ha','ha','ha'],

})
print(our_teachers)

our_teachers.to_excel('teachers.xlsx')